name: ProTReND CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  neo:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        neo4j-version: [ "4.2.5" ]
    services:
      neo4j:
        image: neo4j:${{ matrix.neo4j-version }}
        ports: [ "7687:7687" ]
        env:
          NEO4J_ACCEPT_LICENSE_AGREEMENT: yes
          NEO4J_AUTH: "neo4j/pass"

  build:
    needs: neo
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 4
      matrix:
        python-version: [3.7, 3.8, 3.9]

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: Install Labels
      run: |
        python src/manage.py install_labels
    - name: Run Tests
      run: |
        python src/manage.py test
